export type SlotStatus = "AVAILABLE" | "BOOKED" | "IN_PROGRESS" | "COMPLETED" | "BLOCKED";

export interface ScheduleSlot {
  id: string;
  doctorId: string;
  doctorName: string;
  doctorNameAr: string;
  dayEn: string;      // e.g. "Sunday"
  dayAr: string;      // e.g. "الأحد"
  time: string;       // e.g. "09:00 AM"
  durationMinutes: number;
  status: SlotStatus;
  
  // Patient info (if booked)
  patientName?: string;
  patientNameAr?: string;
  patientPhone?: string;
  patientAge?: number;
  appointmentType?: string;
  appointmentTypeAr?: string;
  fee?: number;
  notes?: string;
}

export const WEEK_DAYS = [
  { en: "Saturday", ar: "السبت", shortEn: "Sat", shortAr: "سبت" },
  { en: "Sunday", ar: "الأحد", shortEn: "Sun", shortAr: "أحد" },
  { en: "Monday", ar: "الاثنين", shortEn: "Mon", shortAr: "اثنين" },
  { en: "Tuesday", ar: "الثلاثاء", shortEn: "Tue", shortAr: "ثلاثاء" },
  { en: "Wednesday", ar: "الأربعاء", shortEn: "Wed", shortAr: "أربعاء" },
  { en: "Thursday", ar: "الخميس", shortEn: "Thu", shortAr: "خميس" },
];

export const INITIAL_SCHEDULE_SLOTS: ScheduleSlot[] = [
  // ─── Dr. Ahmed Hossam (doc-1) - Sunday ───
  {
    id: "slot-101",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "09:00 AM",
    durationMinutes: 30,
    status: "COMPLETED",
    patientName: "Ahmed Hassan",
    patientNameAr: "أحمد حسن",
    patientPhone: "+20 100 123 4567",
    patientAge: 42,
    appointmentType: "Follow-up Check",
    appointmentTypeAr: "متابعة دورية",
    fee: 300,
    notes: "Regular blood pressure check.",
  },
  {
    id: "slot-102",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "09:30 AM",
    durationMinutes: 30,
    status: "IN_PROGRESS",
    patientName: "Omar Farouk",
    patientNameAr: "عمر فاروق",
    patientPhone: "+20 101 234 5678",
    patientAge: 38,
    appointmentType: "Consultation & ECG",
    appointmentTypeAr: "كشف ورسم قلب",
    fee: 450,
    notes: "Patient arrived on time, currently in exam room #1.",
  },
  {
    id: "slot-103",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "10:00 AM",
    durationMinutes: 30,
    status: "AVAILABLE",
  },
  {
    id: "slot-104",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "10:30 AM",
    durationMinutes: 30,
    status: "BOOKED",
    patientName: "Sara Ibrahim",
    patientNameAr: "سارة إبراهيم",
    patientPhone: "+20 102 345 6789",
    patientAge: 29,
    appointmentType: "New Patient Consultation",
    appointmentTypeAr: "كشف مريض جديد",
    fee: 400,
    notes: "Palpitations inquiry sent via WhatsApp.",
  },
  {
    id: "slot-105",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "11:00 AM",
    durationMinutes: 30,
    status: "BOOKED",
    patientName: "Mohamed Ali",
    patientNameAr: "محمد علي",
    patientPhone: "+20 103 456 7890",
    patientAge: 55,
    appointmentType: "Post-Op Wound Check",
    appointmentTypeAr: "فحص جرح بعد القسطرة",
    fee: 250,
  },
  {
    id: "slot-106",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "11:30 AM",
    durationMinutes: 30,
    status: "AVAILABLE",
  },
  {
    id: "slot-107",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "12:00 PM",
    durationMinutes: 30,
    status: "BLOCKED",
    notes: "Doctor clinical break & hospital coordination",
  },
  {
    id: "slot-108",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "12:30 PM",
    durationMinutes: 30,
    status: "AVAILABLE",
  },
  {
    id: "slot-109",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "01:00 PM",
    durationMinutes: 30,
    status: "BOOKED",
    patientName: "Fatima Omar",
    patientNameAr: "فاطمة عمر",
    patientPhone: "+20 104 567 8901",
    patientAge: 34,
    appointmentType: "Prescription Renewal",
    appointmentTypeAr: "تجديد روشتة",
    fee: 200,
  },
  {
    id: "slot-110",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "01:30 PM",
    durationMinutes: 30,
    status: "BOOKED",
    patientName: "Nouran Mahmoud",
    patientNameAr: "نوران محمود",
    patientAge: 32,
    patientPhone: "+20 102 345 6789",
    appointmentType: "Diabetes & Heart Follow-up",
    appointmentTypeAr: "متابعة السكر والقلب",
    fee: 350,
  },
  {
    id: "slot-111",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "02:00 PM",
    durationMinutes: 30,
    status: "AVAILABLE",
  },

  // ─── Dr. Tarek Omar (doc-2) - Sunday ───
  {
    id: "slot-201",
    doctorId: "doc-2",
    doctorName: "Dr. Tarek Omar",
    doctorNameAr: "د. طارق عمر",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "10:00 AM",
    durationMinutes: 30,
    status: "BOOKED",
    patientName: "Hany Youssef",
    patientNameAr: "هاني يوسف",
    patientPhone: "+20 103 456 7890",
    patientAge: 58,
    appointmentType: "GERD & Internal Check",
    appointmentTypeAr: "فحص ارتجاع المريء والباطنة",
    fee: 400,
  },
  {
    id: "slot-202",
    doctorId: "doc-2",
    doctorName: "Dr. Tarek Omar",
    doctorNameAr: "د. طارق عمر",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "10:30 AM",
    durationMinutes: 30,
    status: "AVAILABLE",
  },
  {
    id: "slot-203",
    doctorId: "doc-2",
    doctorName: "Dr. Tarek Omar",
    doctorNameAr: "د. طارق عمر",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "11:00 AM",
    durationMinutes: 30,
    status: "AVAILABLE",
  },
  {
    id: "slot-204",
    doctorId: "doc-2",
    doctorName: "Dr. Tarek Omar",
    doctorNameAr: "د. طارق عمر",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "11:30 AM",
    durationMinutes: 30,
    status: "BOOKED",
    patientName: "Mariam Khaled",
    patientNameAr: "مريم خالد",
    patientPhone: "+20 104 567 8901",
    patientAge: 27,
    appointmentType: "Digestive Follow-up",
    appointmentTypeAr: "متابعة جهاز هضمي",
    fee: 250,
  },

  // ─── Dr. Sara Kamal (doc-3) - Sunday ───
  {
    id: "slot-301",
    doctorId: "doc-3",
    doctorName: "Dr. Sara Kamal",
    doctorNameAr: "د. سارة كمال",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "01:00 PM",
    durationMinutes: 30,
    status: "BOOKED",
    patientName: "Omar Sherif (Child)",
    patientNameAr: "عمر شريف (طفل)",
    patientPhone: "+20 105 678 9012",
    patientAge: 5,
    appointmentType: "Pediatric Follow-up",
    appointmentTypeAr: "متابعة أطفال ونزلة معوية",
    fee: 350,
  },
  {
    id: "slot-302",
    doctorId: "doc-3",
    doctorName: "Dr. Sara Kamal",
    doctorNameAr: "د. سارة كمال",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "01:30 PM",
    durationMinutes: 30,
    status: "AVAILABLE",
  },
  {
    id: "slot-303",
    doctorId: "doc-3",
    doctorName: "Dr. Sara Kamal",
    doctorNameAr: "د. سارة كمال",
    dayEn: "Sunday",
    dayAr: "الأحد",
    time: "02:00 PM",
    durationMinutes: 30,
    status: "AVAILABLE",
  },

  // ─── Monday Slots ───
  {
    id: "slot-401",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Monday",
    dayAr: "الاثنين",
    time: "09:00 AM",
    durationMinutes: 30,
    status: "AVAILABLE",
  },
  {
    id: "slot-402",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Monday",
    dayAr: "الاثنين",
    time: "09:30 AM",
    durationMinutes: 30,
    status: "BOOKED",
    patientName: "Kareem Tarek",
    patientNameAr: "كريم طارق",
    patientPhone: "+20 100 123 4567",
    patientAge: 46,
    appointmentType: "Cardiac Consultation",
    appointmentTypeAr: "كشف قلب",
    fee: 400,
  },
  {
    id: "slot-403",
    doctorId: "doc-1",
    doctorName: "Dr. Ahmed Hossam",
    doctorNameAr: "د. أحمد حسام",
    dayEn: "Monday",
    dayAr: "الاثنين",
    time: "10:00 AM",
    durationMinutes: 30,
    status: "AVAILABLE",
  },
];
